version: '3.2'

services:
    jupyterhub:
        build:
            context: ./docker/
            args:
                BASE_IMAGE: jupyterhub/jupyterhub:1.3.0
        image: brazildatacube/jupyterhub:1.0.0
        container_name: bdc-jupyterhub
        hostname: bdc-jupyterhub
        volumes:
            -   type: bind
                source: ./config/jupyterhub_config.py
                target: /srv/jupyterhub/jupyterhub_config.py
            -   type: bind
                source: ./config/users.json
                target: /srv/jupyterhub/users.json
            -   type: bind
                source: ./config/images.json
                target: /srv/jupyterhub/images.json
            -   type: bind
                source: /var/run/docker.sock
                target: /var/run/docker.sock
            -   type: volume
                source: jupyterhub_data
                target: "/srv/jupyterhub"
            -   type: bind
                source: ${USERS_BASE_DIR_SOURCE}
                target: ${USERS_BASE_DIR_TARGET}
        env_file:
            - ./.env
        environment:
            - HOST
        ports:
            - "8000:8000"
        restart: unless-stopped
        networks:
            - bdc-jupyterhub-net


volumes:
  jupyterhub_data:

networks:
    bdc-jupyterhub-net:
        external:
            name: ${DOCKER_NETWORK_NAME}