version: '3.2'

services:
    jupyterhub:
        image: bdc/jupyterhub:1.0.0
        container_name: bdc-jupyterhub
        volumes:
            -   type: bind
                source: ./docker/jupyterhub/jupyterhub_config.py
                target: /srv/jupyterhub/jupyterhub_config.py
            -   type: bind
                source: ./docker/jupyterhub/users.json
                target: /srv/jupyterhub/users.json
            -   type: bind
                source: ./docker/jupyterhub/images.json
                target: /srv/jupyterhub/images.json
            -   type: bind
                source: /var/run/docker.sock
                target: /var/run/docker.sock
            -   type: volume
                source: jupyterhub_data
                target: "/srv/jupyterhub"
            -   type: bind
                source: ${USERS_BASE_DIR_SOURCE}
                target: ${USERS_BASE_DIR_TARGET}
        env_file:
            - ./.env
        environment:
            - HOST
        ports:
            - "8000:8000"
        restart: unless-stopped
        networks:
            - bdc-jupyterhub-net

#    postgis:
#        image: postgis/postgis:13-3.1
#        env_file:
#            - .env
#        ports:
#            - "5432:5432"
#        restart: unless-stopped
#        networks:
#            - ${DOCKER_NETWORK_NAME}

volumes:
  jupyterhub_data:

networks:
    bdc-jupyterhub-net:
        external:
            name: ${DOCKER_NETWORK_NAME}